### ISSUE TITLE
Issue parsing title

### ISSUE THREAD

**Issue by teebling** [s9e/phpbb-ext-internal-links-title#1]
Hi JoshyPHP,

I imagine just from glancing at the code that this ext detects internal domain links, grabs the title of the target page's URL, and places this within the anchor tag? If that's right OMG that would be so awesome.

I've been doing some tests on phpBB 3.3.0 on localhost:8888 (XAMMP) - it looks like it correctly identifies that the URL I've put in is an internal one, but it looks like it doesn't parse the page title correctly and returns a random alphanumeric string:

![Screen Shot 2020-06-19 at 00 07 35](https://user-images.githubusercontent.com/49092979/85080544-5d479c00-b1c1-11ea-9132-e6f053535500.png)

Is this just because I'm on a localhost environment?

Thanks,
Teebling :)

**Comment by JoshyPHP** [comment]
No, that's just a bug. The correct title gets encoded but if it's too long it ends up being truncated by phpBB and it can't be decoded anymore.

The extension should be redone to work differently and not encode titles at all.
